In [2]:
import numpy as np
import matplotlib.pyplot as plt

#### Adaline
#### O/P = bias + lr(target - Yin)
#### Yin = weights dot ip

In [3]:
class Adaline:
    def __init__(self,weights,bias,size=None):
        if weights is None:
            self.weights = np.random.rand(size)
            self.bias = np.random.rand(1)
        else:
            self.weights = weights
            self.bias = bias

    def train(self,ip,op,lr=0.1):
        for i in range(len(ip)):
            Yin = np.dot(ip[i],self.weights) + self.bias
            k = lr *(op[i] - Yin)
            self.bias = self.bias + k
            for j in range(ip.shape[1]):
                self.weights[j] = self.weights[j] + k*ip[i][j]
            print(self.weights,self.bias)
        return self.weights, self.bias

In [4]:
a = Adaline(np.array([0.1 ,0.1]), np.array(0.1))

In [9]:
op=op.reshape(4,-1)
op.shape

(4, 1)

In [6]:
ip = np.array([[1,1],[1,-1],[-1,1],[-1,-1]])
op = np.array([1,1,1,-1])

In [7]:
a.train(ip,op)

[0.17 0.17] 0.16999999999999998
[0.253 0.087] 0.253
[0.1617 0.1783] 0.3443
[0.26213 0.27873] 0.24386999999999998


(array([0.26213, 0.27873]), 0.24386999999999998)

In [8]:
a.train(ip,op)

[0.283657 0.300257] 0.265397
[0.3587773 0.2251367] 0.3405173
[0.27946497 0.30444903] 0.41982963000000006
[0.36305653 0.38804059] 0.33623806700000003


(array([0.36305653, 0.38804059]), 0.33623806700000003)

In [10]:
a.train(ip,op)

[0.35432301 0.37930707] [0.32750455]
[0.42407096 0.30955912] [0.3972525]
[0.35234503 0.38128506] [0.46897843]
[0.42587987 0.45481989] [0.3954436]


(array([0.42587987, 0.45481989]), array([0.3954436]))